name: Twilight Kernel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set Current Date
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential gcc-aarch64-linux-gnu -y

      - name: Build
        run: bash build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}-${{ matrix.variant }}-${{ matrix.ksu }}-${{ matrix.susfs }}-${{ matrix.selinux }}
          path: "out/"
